/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthenticatedUsersNewuserRouteImport } from './routes/_authenticated/users/newuser'
import { Route as AuthenticatedUsersListuserRouteImport } from './routes/_authenticated/users/listuser'
import { Route as AuthenticatedProjectNewRouteImport } from './routes/_authenticated/project/new'
import { Route as AuthenticatedProjectListRouteImport } from './routes/_authenticated/project/list'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedUsersNewuserRoute =
  AuthenticatedUsersNewuserRouteImport.update({
    id: '/users/newuser',
    path: '/users/newuser',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersListuserRoute =
  AuthenticatedUsersListuserRouteImport.update({
    id: '/users/listuser',
    path: '/users/listuser',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectNewRoute = AuthenticatedProjectNewRouteImport.update({
  id: '/project/new',
  path: '/project/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectListRoute =
  AuthenticatedProjectListRouteImport.update({
    id: '/project/list',
    path: '/project/list',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginRoute
  '/about': typeof AuthenticatedAboutRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/project/list': typeof AuthenticatedProjectListRoute
  '/project/new': typeof AuthenticatedProjectNewRoute
  '/users/listuser': typeof AuthenticatedUsersListuserRoute
  '/users/newuser': typeof AuthenticatedUsersNewuserRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/about': typeof AuthenticatedAboutRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/project/list': typeof AuthenticatedProjectListRoute
  '/project/new': typeof AuthenticatedProjectNewRoute
  '/users/listuser': typeof AuthenticatedUsersListuserRoute
  '/users/newuser': typeof AuthenticatedUsersNewuserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/project/list': typeof AuthenticatedProjectListRoute
  '/_authenticated/project/new': typeof AuthenticatedProjectNewRoute
  '/_authenticated/users/listuser': typeof AuthenticatedUsersListuserRoute
  '/_authenticated/users/newuser': typeof AuthenticatedUsersNewuserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/about'
    | '/profile'
    | '/settings'
    | '/'
    | '/project/list'
    | '/project/new'
    | '/users/listuser'
    | '/users/newuser'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/about'
    | '/profile'
    | '/settings'
    | '/'
    | '/project/list'
    | '/project/new'
    | '/users/listuser'
    | '/users/newuser'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/login'
    | '/_authenticated/about'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/project/list'
    | '/_authenticated/project/new'
    | '/_authenticated/users/listuser'
    | '/_authenticated/users/newuser'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/users/newuser': {
      id: '/_authenticated/users/newuser'
      path: '/users/newuser'
      fullPath: '/users/newuser'
      preLoaderRoute: typeof AuthenticatedUsersNewuserRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/listuser': {
      id: '/_authenticated/users/listuser'
      path: '/users/listuser'
      fullPath: '/users/listuser'
      preLoaderRoute: typeof AuthenticatedUsersListuserRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/new': {
      id: '/_authenticated/project/new'
      path: '/project/new'
      fullPath: '/project/new'
      preLoaderRoute: typeof AuthenticatedProjectNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/list': {
      id: '/_authenticated/project/list'
      path: '/project/list'
      fullPath: '/project/list'
      preLoaderRoute: typeof AuthenticatedProjectListRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProjectListRoute: typeof AuthenticatedProjectListRoute
  AuthenticatedProjectNewRoute: typeof AuthenticatedProjectNewRoute
  AuthenticatedUsersListuserRoute: typeof AuthenticatedUsersListuserRoute
  AuthenticatedUsersNewuserRoute: typeof AuthenticatedUsersNewuserRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProjectListRoute: AuthenticatedProjectListRoute,
  AuthenticatedProjectNewRoute: AuthenticatedProjectNewRoute,
  AuthenticatedUsersListuserRoute: AuthenticatedUsersListuserRoute,
  AuthenticatedUsersNewuserRoute: AuthenticatedUsersNewuserRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
